#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OGUzOWViOGQ4NTZmZTAwZmY2YjNkMzg1YjUyNTgxZjg5OGU3YWM3NzFjNzZmODZiMGMwNmM4YTliZTZlNzRhZTRiZGIwNDdiMWI4NmZlMjI3MzlhYzJkODc0Njk2M2QyN2FiYg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-10487447.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oa7tu9fx2sJUkPYX5d6
            client-secret: rQVU3Dsg0ld6gNAQyFhaLu46GUfTZ7yFivH9BaRE

